---

- name: install nginx
  apt: pkg=nginx state=installed

- name: disable default site
  file: path=/etc/nginx/sites-enabled/default state=absent
  notify: reload nginx

- name: nginx service on boot
  service: name=nginx enabled=yes

- name: create ssl key directory
  file: path=/etc/nginx/ssl state=directory
